Dive_Deep_Into_CircleStarks
invisible-garden/cm24-projects pull request #34
Opened 2024-11-06 05:50 UTC by YangXiaoXue205

2024-11-08 03:55 UTC, rutefig requested changes
Other that this small things everything is good 🚀

2024-11-08 03:55 UTC, rutefig commented on Dive_Deep_Into_CircleStarks/README.md
> +# {Project Name}
can you add the name of the project here pls? (pls remove the `{` when you replace the requested data

2024-11-08 03:55 UTC, rutefig commented on Dive_Deep_Into_CircleStarks/README.md
> +- Name: {YangXiaoXue}
Pls remove the `{` `}` after the data being replaced

2024-11-08 14:24 UTC, rutefig commented
@YangXiaoXue205 can you check the comments pls?

2024-11-27 02:56 UTC, YangXiaoXue205 commented
Sorry, I just saw the comment, I just commited it

2024-11-28 11:05 UTC, rutefig approved these changes

2024-11-28 11:06 UTC, merged